export const META = {
  TITLE: 'epoxide',
  DESCRIPTION: 'Library and landing page for epoxide.',
  THEME: 'dark',
  SITE_NAME: 'epoxide',
  URL: 'https://epoxide.se',
  LOCALE: 'en-US',
  TYPE: 'website' as const,
  OG_IMAGE: '/opengraph-image.png',
  TWITTER_IMAGE: '/twitter-image.png',
  TWITTER_CREATOR: '@TLEpoxide',
  TWITTER_CREATOR_ID: '870776905',
  TWITTER_CARD: 'summary_large_image' as const,
  GOOGLE_SITE_VERIFICATION: 'wzqG8ce2wQmwPODNX0HFf9TtNr5xSedSfF6_0nZKWMc',
}
